Styles fixing with stylelint fix saas
KosSid/fe-19-final-project-baber-shop pull request #75
Opened 2021-02-18 09:08 UTC by KosSid

styles files fixing with stylelint-fix-saas script to avoid mistakes in the console

2021-02-18 20:01 UTC, Sofi-Franko approved these changes

2021-02-18 21:19 UTC, SelikBready approved these changes

2021-02-18 21:22 UTC, SelikBready requested changes, later dismissed
Очень много изменений повторяется с https://github.com/KosSid/fe-19-final-project-baber-shop/pull/74/files. Поправь плиз, не делай ветки одну из другой, каждая ветка должна создаваться из девелопа и отражать изменения, которые делаются, относительно него.

2021-02-18 23:55 UTC, peksymov approved these changes

2021-02-18 23:56 UTC, KosSid commented
> Очень много изменений повторяется с https://github.com/KosSid/fe-19-final-project-baber-shop/pull/74/files. Поправь плиз, не делай ветки одну из другой, каждая ветка должна создаваться из девелопа и отражать изменения, которые делаются, относительно него.

Вот эту ветку оставил. В ней все финальный апдейты есть

2021-02-19 09:27 UTC, vrindislam approved these changes

2021-02-19 09:45 UTC, merged